// layout.tsx

// [@-- section="MetaDeta"]
export const metadata = {
    title: 'SignIn',
    description: 'Generated by vortex core cli'
}
// [/@--]

// [@-- section="Code"]
export default function RootLayout({
    children
}: {
    children: React.ReactNode
}) {
    // ------------------------------------------------------------------------

    return (
        // [@-- section="TSX" type="default"]

        <div className="surface-ground h-screen w-screen px-4 py-8 md:px-6 lg:px-8 flex align-items-center justify-content-center">
            {/* Children */}
            {children}
        </div>

        // [/@--]
    )

    //
}
// [/@--]

// EOF
