// layout.tsx

// [@-- section="ResetCss" type="import" comment="A modern CSS reset"]
import 'modern-css-reset/dist/reset.min.css'
// [/@--]

// [@-- section="PrimeFlex" type="import"]
import 'primeflex/primeflex.css'
// [/@--]

// [@-- section="PrimeIcons" type="import"]
import 'primeicons/primeicons.css'
// [/@--]

// [@-- section="PrimeReact" type="import"]
import 'primereact/resources/primereact.min.css'
import '@/libs/vortexcore/primereact/locale-ja'
import '@/libs/vortexcore/primereact/light-theme.css'
import '@/libs/vortexcore/primereact/dark-theme.css'
// [/@--]

// [@-- section="CustomCSS" type="import"]
import '@/app/globals.css'
// [/@--]

// [@-- section="MiscFunctions" type="import"]
import getDarkModeClass from '@/libs/vortexcore/misc/getDarkModeClass'
import getDict from '@/libs/vortexcore/misc/getDictionary'
import getLang from '@/libs/vortexcore/misc/getLangByServer'
// [/@--]

// [@-- section="AppProvider" type="import"]
import AppProvider from '@/app/_providers/AppProvider'
// [/@--]

// [@-- section="GoogleFont" type="import"]
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })
// [/@--]

// [@-- section="MetaDeta"]
export const metadata = {
    title: 'Vortex Core App',
    description: 'Generated by vortex core cli'
}
// [/@--]

// [@-- section="Code"]
export default async function AppLayout({
    children
}: {
    children: React.ReactNode
}) {
    // [@-- section="BodyTagClasses"]

    // set body tag classes
    const bodyClasses = [inter.className, getDarkModeClass()].join(' ')

    // [/@--]

    // [@-- section="Dictionary"]

    const dictionary = await getDict()

    // [/@--]

    // ------------------------------------------------------------------------

    return (
        // [@-- section="TSX" type="default"]

        // set lang attribute by @/libs/vortexcore/misc/getLang
        <html lang={getLang()}>
            {/* Body */}
            <body className={bodyClasses}>
                <AppProvider
                    // specify lang attribute by @/libs/vortexcore/misc/getLang
                    lang={getLang()}
                    //
                    // specify dictionary by @/libs/vortexcore/misc/getDictionary
                    dictionary={dictionary}
                    //
                >
                    {/* Children */}
                    {children}
                </AppProvider>
            </body>
        </html>

        // [/@--]
    )

    //
}
// [/@--]

// EOF
