// layout.tsx

// A modern CSS reset
import 'modern-css-reset/dist/reset.min.css'

// PrimeFlex
import 'primeflex/primeflex.css'

// PrimeIcons
import 'primeicons/primeicons.css'

// PrimeReact
import 'primereact/resources/primereact.min.css'
import '@/libs/primereact/light-theme.css'
import '@/libs/primereact/dark-theme.css'

import '@/app/globals.css'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'Vortex Core App',
    description: 'Generated by vortex core cli'
}

export default function SignInLayout({
    children,
    params: { lang }
}: {
    children: React.ReactNode
    params: { lang: string }
}) {
    // set cookies
    const cookieStore = cookies()

    // set darkmode state from cookie
    const cookieDarkMode = cookieStore.get('dark-mode')

    // ------------------------------------------------------------------------

    return (
        <html lang={lang}>
            <body
                className={`${inter.className} ${
                    cookieDarkMode?.value === 'true' ? 'dark-mode' : ''
                }`}
            >
                {/* Children */}
                {children}
            </body>
        </html>
    )

    //
}

// EOF
