// layout.tsx

import '@/app/globals.css'
import 'primeflex/primeflex.css'
import 'primeicons/primeicons.css'
import 'primereact/resources/themes/lara-light-blue/theme.css'
import 'primereact/resources/primereact.min.css'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
    title: 'SignIn',
    description: 'Generated by vortex core cli'
}

export default function RootLayout({
    children,
    params: { lang }
}: {
    children: React.ReactNode
    params: { lang: string }
}) {
    // ------------------------------------------------------------------------

    return (
        <div className="surface-ground h-screen w-screen px-4 py-8 md:px-6 lg:px-8 flex align-items-center justify-content-center">
            {/* Children */}
            {children}
        </div>
    )

    //
}

// EOF
